FROM node:22-alpine

WORKDIR /app

# Copia dependências do backend
COPY backend/package*.json ./backend/
WORKDIR /app/backend
RUN npm install --production

# Copia código fonte do backend e frontend estático
WORKDIR /app
COPY backend ./backend
COPY frontend ./frontend

WORKDIR /app/backend

EXPOSE 3000

CMD ["node", "src/server.js"]
